### ISSUE TITLE
Update pull request checklist to align with updated contribution requirements (i.e. for black, flake8, ./setup.sh and ./test.sh)

### ISSUE THREAD

**Issue by joehiggi1758** [TDAmeritrade/stumpy#1010]
The current checklist for opening a pull request conflicts with the contributing guide. The contributing guide is as follows...
![image](https://github.com/user-attachments/assets/83ead569-364b-4acd-beb8-b9ec8072e0c2)

While the pull request checklist is as follows...
```
# Pull Request Checklist

Below is a simple checklist but please do not hesitate to ask for assistance!

- [x] Fork, clone, and checkout the newest version of the code
- [x] Create a new branch
- [x] Make necessary code changes
- [x] Install `black` (i.e., `python -m pip install black` or `conda install -c conda-forge black`)
- [x] Install `flake8` (i.e., `python -m pip install flake8` or `conda install -c conda-forge flake8`)
- [x] Install `pytest-cov` (i.e., `python -m pip install pytest-cov` or `conda install -c conda-forge pytest-cov`)
- [x] Run `black .` in the root stumpy directory
- [x] Run `flake8 .` in the root stumpy directory
- [x] Run `./setup.sh && ./test.sh` in the root stumpy directory
- [x] Reference a Github issue (and create one if one doesn't already exist)

```

The pull request checklist should be updated to reflect recent changes surrounding running black, flake8 and ./setup.sh as well as ./test.sh.

**Comment by seanlaw** [comment]
@joehiggi1758 Would you like to tackle this as well? I think you will need to update this file: 

https://github.com/TDAmeritrade/stumpy/blob/main/docs/pull_request_template.md

I think it would make more sense for it to be:

```
# Pull Request Checklist

Below is a simple checklist but please do not hesitate to ask for assistance!

- [ ] Fork, clone, and checkout the newest version of the code
- [ ] Create a new branch
- [ ] Run `./setup.sh dev` (or `./conda.sh` for `conda` users) to install all dependencies 
- [ ] Make necessary code changes
- [ ] Run `black --exclude=".*\.ipynb" --extend-exclude=".venv" --diff ./` in the root stumpy directory
- [ ] Run `flake8 --extend-exclude=.venv ./` in the root stumpy directory
- [ ] Run `./setup.sh && ./test.sh` in the root stumpy directory
- [ ] Reference a Github issue (and create one if one doesn't already exist)
```

**Comment by seanlaw** [comment]
Also, in the future, it would be better to avoid pasting an image of code into a comment and, instead, use triple backticks:

````
```
paste python code in between triple backticks (it is usually the key located to the left of `1`)
```
````

**Comment by joehiggi1758** [comment]
@seanlaw 

- Regarding the image of code: I've updated the original issue raised to reflect this, and will follow that going forward! Thanks for the direction!
- Regarding other updates to the contribution guide: there was one dependency that was required to run tests but wasn't called out in the contributing guide. I'll look into which one it was - because tbh I can't remember off the top of my head
- I'd love to tackle this one - I will give it a crack!
